name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Semver tag
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x

      - name: Setup Nest
        run: |
          deno install -qA ./nest.ts
          nest login nest ${{ secrets.NEST_TOKEN }} -L debug
          nest setup nest nest -L debug

      - name: Publish
        run: nest publish ${{ github.event.inputs.version }} -Y -L debug

      # TODO(@maximousblk): Add a changelog generator

      - name: Release ${{ matrix.tag }}
        uses: ncipollo/release-action@v1
        with:
          tag: '${{ github.event.inputs.repo }}'
          name: '${{ github.event.inputs.repo }}'
          body: ""
          # bodyFile: 'CHANGELOG.md'
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
