name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Semver tag
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.7.2

#       TODO(@maximousblk): enable when the cli is ready to use

#       - name: Setup Nest
#         run: |
#           deno install -qA ./nest.ts
#           nest login nest ${{ secrets.NEST_TOKEN }}
#           nest setup nest nest

#       - name: Publish
#         run: nest publish ${{ github.event.inputs.version }} -Y

      - name: Generate Release Notes
        # TODO(@maximousblk): switch to nest when new registry is released
        run: deno run -A https://deno.land/x/ghlog@0.2.0/ghlog.ts ${{ github.repository }} -v '${{ github.event.inputs.version }}'

      - name: Release ${{ matrix.tag }}
        uses: ncipollo/release-action@v1
        with:
          tag: '${{ github.event.inputs.version }}'
          name: 'v${{ github.event.inputs.version }}'
          bodyFile: 'CHANGELOG.md'
          draft: true
          token: ${{ secrets.GITHUB_TOKEN }}
