name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x

      - name: Run Tests
        run: deno test -A

      - name: Setup Nest
        run: |
          deno install -qA ./nest.ts
          nest login nest ${{ secrets.NEST_TOKEN }} -L debug
          nest setup nest nest -L debug

      - name: Dry publish
        run: nest publish 0.0.0 --pre dev -Yd -L debug

      - name: Upload debug file
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: debug-files
          path: ~/.nest/logs/*
