name: Test

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x

      - name: Run Tests
        run: deno test -A

      - name: Setup Nest
        run: |
          deno install -qA ./nest.ts
          nest login nest ${{ secrets.NEST_TOKEN }}
          nest setup nest nest

      - name: Dry publish
        run: nest publish -Yd 0.0.0 --pre dev

      - name: Upload debug file
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: debug-files
          path: /home/runner/.nest/logs/*
